*

diff --git a/mmu/usr/local/bin/manage-users b/mmu/usr/local/bin/manage-users
--- a/mmu/usr/local/bin/manage-users
+++ b/mmu/usr/local/bin/manage-users
@@ -14,90 +14,129 @@ exists(){
     return $? 
 }
 
+RED='\033[43m'      # Yellow Background
+#RED='\033[41m'         # Red Background
+red='\033[0;31m'
+NC='\033[0m' # No Color
+#echo -e "I ${RED}love${NC} Stack Overflow"
 
+
+echo "info: checking input ..."
+
+CNT=0
 ERR="false"
+while IFS="," read -r uid passwd name type group extra; do
 
-while IFS="," read -r uid passwd name type group; do
-    if test -n "$uid"; then
-	if [[ "$type" =~ ^(admin|teacher|student)$ ]]; then
-	    if [[ "$passwd" =~ ^.{4,16}$ ]]; then
-		if ! [[ "$uid" =~ ^[abcdefghijklmnopqrstuvwxyz_][abcdefghijklmnopqrstuvwxyz0123456789._]{0,31}$ ]]; then 
-		    echo "error: username \"$uid\" is not allowed" >&2
-		    ERR="true"
-		fi
-	    else
-		echo "error: $uid"
-		ERR="true"
-	    fi
+    cnt=$(( cnt + 1 ))
+    
+    E_passwd=false
+    if ! [[ "$passwd" =~ ^.{4,16}$ ]]; then
+	E_passwd=true
+    fi
+    
+    E_uid=false
+    if ! [[ "$uid" =~ ^[abcdefghijklmnopqrstuvwxyz_][abcdefghijklmnopqrstuvwxyz0123456789._-]{0,31}$ ]]; then 
+	E_uid=true
+    fi
+
+    E_type=false
+    if ! [[ "$type" =~ ^(admin|teacher|student)$ ]]; then
+	E_type=true
+    fi
+
+    E_extra=false
+    if test -n "$extra"; then
+        E_extra=true
+    fi
+       
+    E_name=false
+    if test -z "$name"; then
+        E_name=true
+    fi
+       
+    if $E_uid || $E_passwd || $E_type || $E_extra || $E_name; then
+	echo -n "    $cnt: "   
+	if $E_uid; then
+	    echo -n -e "|$RED$uid$NC|"
 	else
-	    echo "error: $uid type not correct"
-	    ERR=true
+	    echo -n -e "|$uid|"
 	fi
-    else
-	echo "error: userid kan not be empty"
+	if $E_passwd; then
+	    test -n "$passwd" || passwd="       "
+	    echo -n -e "$RED$passwd$NC|"
+	else
+	    echo -n -e "$passwd|"
+	fi
+	if $E_name; then
+	    echo -n -e "$RED         $NC|"
+	else
+	    echo -n "$name|"
+	fi
+	if $E_type; then
+	    test -n "$type" || type="      ";
+	    echo -n -e "$RED$type$NC|"
+	else
+	    echo -n -e "$type|"
+	fi
+	if test -n "$group"; then
+	   echo -n "$group|"
+	else
+	    echo -n "          |"
+	fi       
+	if $E_extra; then
+	    echo  -e "$RED$extra$NC"
+	else
+	    #echo -e "$extra|"
+	    echo
+	fi
 	ERR=true
-    fi
+    fi       
 done < "$1"
-
-echo " ">alle.txt
-getent passwd | while IFS=":" read -r uider passwd nuid rest; do
-    if test $nuid -ge 1001 -a $nuid -lt 5000;then
-	#echo $nuid $uider
-	echo "$uider">>alle.txt
-    fi
-done
 
 if test $ERR = "false"; then
     echo "info: input file ok"
 
     PFAD="/var/ltsp/users/"
-    if ! test -d $PFAD; then
-	mkdir -p $PFAD
-	chmod 700 $PFAD
+    if ! test -d "$PFAD"; then
+	mkdir -p "$PFAD"
+	chmod 700 "$PFAD"
     fi
 
     echo -n "" > newusers.cmd
-    
-    
     while IFS="," read -r uid passwd name type group; do
        LINE="$uid:$passwd:::$name,$type,$group:/home/$uid:/usr/bin/bash"
-       if ! exists "$uid";then
+       if ! exists "$uid"; then
 	   echo  "$LINE" >> newusers.cmd
-	   echo "$LINE" > $PFAD/$uid
+	   echo "$LINE" > "$PFAD/$uid"
 	   echo "      create $uid"
        else
-	   if test -f  $PFAD/$uid; then
-	       LINE_ALT=$(cat  $PFAD/$uid)
+	   if test -f  "$PFAD/$uid"; then
+	       LINE_ALT=$(cat  "$PFAD/$uid")
 	   else
 	       LINE_ALT=""
 	   fi
 	   if ! test "$LINE" = "$LINE_ALT"; then
 	       echo "$LINE" >> newusers.cmd
-	       echo "$LINE" >  $PFAD/$uid
+	       echo "$LINE" >  "$PFAD/$uid"
 	       echo "      modify $uid"
 #	   else
 #	       echo "             $uid"
 	   fi
 	   
        fi
+       
  
      done < "$1"
 
-     if newusers newusers.cmd;then
+     if newusers newusers.cmd; then
         echo "info: alles ok"
 	rm newusers.cmd
      else
 	echo "error: nummer $?"
-     fi
-	
-	   
-	   
-
-    
-    
+     fi    
 else
-    echo 
-    echo "error: es gab fehler in den namen" >&2
+    echo
+    echo -e "${red}error: es gab fehler im eingabefile$NC" >&2
 fi
 
 
